"""empty message

Revision ID: 16ed7c4a72bf
Revises: ef79c8d003d
Create Date: 2015-03-22 13:54:14.064721

"""

# revision identifiers, used by Alembic.
revision = '16ed7c4a72bf'
down_revision = 'ef79c8d003d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###
