"""empty message

Revision ID: ef79c8d003d
Revises: None
Create Date: 2015-03-22 13:52:07.484534

"""

# revision identifiers, used by Alembic.
revision = 'ef79c8d003d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
